name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup pyton 3.9.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U wheel coverage pytest black
      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
      - name: Check with black
        run: |
          black --check .
      - name: Push coverage to coveralls
        run: |
          pip install -U coveralls
          coveralls
